def test_failure_example(self):
    self.assertEqual(2 * 2, 5)  # intentional fail
